// Generated by https://quicktype.io

export interface TopTenByTimeRangeReport {
    morning: number;
    afternoon: number;
    evening: number;
}

// Generated by https://quicktype.io

export interface TopTenByZoneReport {
    id: number;
    zoneName: string;
    morning: number;
    afternoon: number;
    evening: number;
    total: number;
}
